# Fly.io configuration for Sentia Manufacturing Dashboard
app = "sentia-manufacturing-dashboard"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile.simple"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[processes]
  app = "node server.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[deploy]
  release_command = "npx prisma migrate deploy && npx prisma generate"

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/public/"

[mounts]
  source = "sentia_data"
  destination = "/data"
