[phases.build]
cmd = "npm ci --no-cache"

[phases.start]
cmd = "node mcp-server.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[nixpacks]
archive = false

[providers.node]
version = "18"