# Railway Deployment Configuration for Sentia Manufacturing Dashboard
# Optimized for Node.js/Express + React/Vite architecture

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.development]
[environments.development.variables]
NODE_ENV = "development"
AUTONOMOUS_SCHEDULER_MODE = "railway"
ENABLE_AUTONOMOUS_TESTING = "true"
AUTO_FIX_ENABLED = "true"
AUTO_DEPLOY_ENABLED = "true"

[environments.testing]
[environments.testing.variables]
NODE_ENV = "test"
AUTONOMOUS_SCHEDULER_MODE = "railway"
ENABLE_AUTONOMOUS_TESTING = "true"
AUTO_FIX_ENABLED = "true"
AUTO_DEPLOY_ENABLED = "false"

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
AUTONOMOUS_SCHEDULER_MODE = "railway"
ENABLE_AUTONOMOUS_TESTING = "false"
AUTO_FIX_ENABLED = "false"
AUTO_DEPLOY_ENABLED = "false"

# Railway-specific optimizations
[nixpacks.config]
install.apt = []
install.libraries = []

# Memory and performance optimization
[deploy.settings]
memory = "2GB"
replicas = 1

# Health monitoring
[monitoring]
enabled = true
cpu.threshold = 80
memory.threshold = 80