[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "node railway-ultimate.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 5000

[environments.development]
NODE_ENV = "development"
RAILWAY_ENVIRONMENT = "development"

[environments.test]
NODE_ENV = "test"
RAILWAY_ENVIRONMENT = "test"

[environments.production]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"