[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "node scripts/enterprise-self-healing-agent.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production.variables]
NODE_ENV = "production"
AUTO_FIX_ENABLED = "true"
AUTO_DEPLOY_ENABLED = "true"
SECURITY_SCAN_ENABLED = "true"
PERFORMANCE_MONITORING = "true"
HEALTH_CHECK_INTERVAL = "600000"
DEEP_SCAN_INTERVAL = "3600000"
CIRCUIT_BREAKER_FAILURE_THRESHOLD = "5"
CIRCUIT_BREAKER_RECOVERY_TIMEOUT = "60000"
LOG_LEVEL = "info"
RAILWAY_DEVELOPMENT_URL = "https://daring-reflection-development.up.railway.app"
RAILWAY_TESTING_URL = "https://sentia-manufacturing-dashboard-testing.up.railway.app"  
RAILWAY_PRODUCTION_URL = "https://web-production-1f10.up.railway.app"