# Railway Configuration for Sentia Manufacturing Dashboard
# Force Node.js detection and proper Docker build

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "echo 'Using Dockerfile build process'"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment detection
[environments.production]
build.dockerfilePath = "./Dockerfile"
deploy.startCommand = "npm start"
deploy.healthcheckPath = "/health"
deploy.restartPolicyType = "ON_FAILURE"

[environments.test]
build.dockerfilePath = "./Dockerfile"
deploy.startCommand = "npm start"
deploy.healthcheckPath = "/health"
deploy.restartPolicyType = "ON_FAILURE"

[environments.development]
build.dockerfilePath = "./Dockerfile"
deploy.startCommand = "npm start"
deploy.healthcheckPath = "/health"
deploy.restartPolicyType = "ON_FAILURE"