# Enhanced Railway Configuration for Sentia Manufacturing Dashboard

[build]
builder = "nixpacks"
buildCommand = "npm run build:railway"
watchPatterns = ["src/**", "server.js", "package.json", "vite.config.js"]

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1

# Development Environment
[environments.development]
variables = { 
  NODE_ENV = "development",
  LOG_LEVEL = "debug",
  RAILWAY_ENVIRONMENT = "development"
}

[environments.development.deploy]
healthcheckTimeout = 180
restartPolicyMaxRetries = 5

# Testing Environment  
[environments.testing]
variables = { 
  NODE_ENV = "testing",
  LOG_LEVEL = "info",
  RAILWAY_ENVIRONMENT = "testing"
}

[environments.testing.deploy]
healthcheckTimeout = 240
restartPolicyMaxRetries = 3

# Production Environment
[environments.production]
variables = { 
  NODE_ENV = "production",
  LOG_LEVEL = "warn",
  RAILWAY_ENVIRONMENT = "production",
  MAX_CONNECTIONS = "100",
  CONNECTION_TIMEOUT = "30000",
  QUERY_TIMEOUT = "60000"
}

[environments.production.deploy]
healthcheckTimeout = 300
restartPolicyMaxRetries = 2
numReplicas = 2

# Resource limits for production
[environments.production.resources]
memory = "2GB"
cpu = "1000m"

# Networking configuration
[networking]
serviceDomain = "sentia-manufacturing"

# Monitoring and observability
[observability]
enableMetrics = true
enableTracing = true

# Build optimization
[build.env]
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_PRODUCTION = "false"

# Cache configuration
[cache]
paths = ["node_modules", ".next/cache", "dist"]

