[build]
builder = "NIXPACKS"
buildCommand = "npm ci --prefer-offline --no-audit && npm run build"

[deploy]
# Use Caddy to serve static files - this fixes blank screen issues
startCommand = "caddy run --config Caddyfile --adapter caddyfile"
healthcheckPath = "/health"
healthcheckTimeout = 45
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "web"
# Railway assigns PORT automatically, Caddyfile uses $PORT
port = 8080