# Render Multi-Environment Configuration
# Deploy all three environments (development, testing, production)

services:
  # ===================================
  # DEVELOPMENT ENVIRONMENT
  # ===================================
  - type: web
    name: sentia-manufacturing-development
    runtime: node
    region: oregon
    plan: free # Use free for development
    branch: development

    buildCommand: npm ci --legacy-peer-deps && npm run build && npx prisma generate && npx prisma db push --skip-generate
    startCommand: node server.js
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: https://sentia-manufacturing-development.onrender.com

      # MCP Server Integration
      - key: MCP_SERVER_URL
        value: https://mcp-server-tkyu.onrender.com
      - key: MCP_WEBSOCKET_URL
        value: wss://mcp-server-tkyu.onrender.com
      - key: MCP_JWT_SECRET
        generateValue: true

      # Database - Development (Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: sentia-db-development
          property: connectionString

      # Include all other environment variables from main render.yaml
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_Y2hhbXBpb24tYnVsbGRvZy05Mi5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_EP6iF7prGbq73CscUPCOW8PAKol4pPaBG5iYdsDodq

  # ===================================
  # TESTING/UAT ENVIRONMENT
  # ===================================
  - type: web
    name: sentia-manufacturing-testing
    runtime: node
    region: oregon
    plan: starter # $7/month for testing
    branch: test

    buildCommand: npm ci --legacy-peer-deps && npm run build && npx prisma generate && npx prisma db push --skip-generate
    startCommand: node server.js
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: test
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: https://sentia-manufacturing-testing.onrender.com

      # MCP Server Integration
      - key: MCP_SERVER_URL
        value: https://mcp-server-tkyu.onrender.com
      - key: MCP_WEBSOCKET_URL
        value: wss://mcp-server-tkyu.onrender.com
      - key: MCP_JWT_SECRET
        generateValue: true

      # Database - Testing (Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: sentia-db-testing
          property: connectionString

      # Include all other environment variables
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_Y2hhbXBpb24tYnVsbGRvZy05Mi5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_EP6iF7prGbq73CscUPCOW8PAKol4pPaBG5iYdsDodq

  # ===================================
  # PRODUCTION ENVIRONMENT
  # ===================================
  - type: web
    name: sentia-manufacturing-production
    runtime: node
    region: oregon
    plan: standard # $25/month for production reliability
    branch: production

    buildCommand: npm ci --legacy-peer-deps && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: node server.js
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: https://sentia-manufacturing-production.onrender.com

      # MCP Server Integration
      - key: MCP_SERVER_URL
        value: https://mcp-server-tkyu.onrender.com
      - key: MCP_WEBSOCKET_URL
        value: wss://mcp-server-tkyu.onrender.com
      - key: MCP_JWT_SECRET
        generateValue: true

      # Database - Production (Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: sentia-db-production
          property: connectionString

      # Include all other environment variables
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_Y2hhbXBpb24tYnVsbGRvZy05Mi5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_EP6iF7prGbq73CscUPCOW8PAKol4pPaBG5iYdsDodq

# Note: This is a simplified version.
# For full deployment, copy all environment variables from the main render.yaml

# ===================================
# DATABASE DEFINITIONS
# ===================================
databases:
  - name: sentia-db-development
    plan: free
    region: oregon

  - name: sentia-db-testing
    plan: free
    region: oregon

  - name: sentia-db-production
    plan: starter # $7/month for production database
    region: oregon