# Render deployment configuration for Sentia MCP Server
# Enterprise-grade standalone deployment with auto-scaling, caching, and monitoring
# Version: 3.1.0 - Single Production MCP Server serving all environments
# Deploys from production branch to: sentia-mcp-production.onrender.com

services:
  # Single Production MCP Server serving all dashboard environments
  - type: web
    name: sentia-mcp-server-production
    env: docker
    plan: pro
    region: oregon
    repo: https://github.com/The-social-drink-company/sentia-ai-manufacturing-app
    branch: production
    rootDir: sentia-mcp-server
    dockerfile: Dockerfile
    healthCheckPath: /health
    autoDeploy: false  # Manual deployment for production
    # Production auto-scaling
    scaling:
      minInstances: 2
      maxInstances: 10
      targetCPUPercent: 60
      targetMemoryPercent: 70
    # Production resource allocation
    disk:
      name: sentia-mcp-prod-disk
      sizeGB: 50
      mountPath: /app/data
    # Blue-green deployment
    deployment:
      strategy: blue-green
      healthCheckGracePeriod: 300s
    envVars:
      - key: NODE_ENV
        value: production
      - key: MCP_SERVER_NAME
        value: sentia-mcp-production
      - key: MCP_SERVER_PORT
        value: 3001
      - key: MCP_TRANSPORT
        value: http
      - key: RENDER
        value: true
      - key: LOG_LEVEL
        value: warn
      - key: AUTH_REQUIRED
        value: true
      - key: RATE_LIMIT_MAX
        value: 100
      # Production performance optimization
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: UV_THREADPOOL_SIZE
        value: 32
      - key: MALLOC_ARENA_MAX
        value: 2
      # Production caching with memory (simplified for initial deployment)
      - key: CACHE_TYPE
        value: memory
      - key: CACHE_TTL
        value: 600000
      - key: CACHE_MAX_SIZE
        value: 10000
      - key: ENABLE_CACHE_COMPRESSION
        value: true
      # Primary database connection (production)
      - key: DATABASE_URL
        fromDatabase:
          name: sentia-manufacturing-production
          property: connectionString
      # Multi-environment database access (MCP server serves all environments)
      - key: DEV_DATABASE_URL
        fromDatabase:
          name: sentia-manufacturing-dev
          property: connectionString
      - key: TEST_DATABASE_URL
        fromDatabase:
          name: sentia-manufacturing-test
          property: connectionString
      - key: PROD_DATABASE_URL
        fromDatabase:
          name: sentia-manufacturing-production
          property: connectionString
      - key: DATABASE_POOL_MAX
        value: 50
      - key: DATABASE_POOL_MIN
        value: 10
      # CORS origins - allow all dashboard environment connections
      - key: CORS_ORIGINS
        value: https://sentia-manufacturing-dashboard-production.onrender.com,https://sentia-manufacturing-dashboard-test.onrender.com,https://sentia-manufacturing-dashboard-621h.onrender.com,http://localhost:3000,http://localhost:5173
      # JWT secret for inter-service communication
      # SECURITY: Set via Render dashboard with 64-character secure random string
      - key: JWT_SECRET
        sync: false  # Must be set manually in Render dashboard
      - key: MCP_JWT_SECRET
        sync: false  # Must be set manually in Render dashboard
      # Production monitoring and observability
      - key: MONITORING_ENABLED
        value: true
      - key: METRICS_ENDPOINT_ENABLED
        value: true
      - key: PERFORMANCE_MONITORING_ENABLED
        value: true
      - key: BUSINESS_ANALYTICS_ENABLED
        value: true
      - key: COLLECT_SYSTEM_METRICS
        value: true
      - key: COLLECT_TOOL_METRICS
        value: true
      - key: PROMETHEUS_METRICS_ENABLED
        value: true
      # Production security hardening
      - key: SECURITY_HEADERS_ENABLED
        value: true
      - key: RATE_LIMITING_ENABLED
        value: true
      - key: INPUT_VALIDATION_STRICT
        value: true
      - key: AUDIT_LOGGING_ENABLED
        value: true
      - key: ENCRYPTION_ENABLED
        value: true
      - key: MFA_ENABLED
        value: true
      # Production alerting
      - key: ALERTING_ENABLED
        value: true
      - key: ALERT_WEBHOOK_ENABLED
        value: true
      - key: ALERT_EMAIL_ENABLED
        value: true
      # Backup and recovery
      - key: BACKUP_ENABLED
        value: true
      - key: BACKUP_RETENTION_DAYS
        value: 30
      - key: AUTO_RECOVERY_ENABLED
        value: true