[providers]
# Explicitly use Node.js only - no Python
node = "18.20.4"

[phases.setup]
# Only Node.js packages
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["mkdir -p logs"]

[start]
cmd = "node enterprise-server-simple.js"
