[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install] 
cmds = ['npm ci --production=false']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '$PORT'
LOG_LEVEL = 'info'
RAILWAY_ENVIRONMENT = 'production'