services:
  # MCP Server - Enterprise AI Central Nervous System
  - type: web
    name: sentia-mcp-server
    runtime: node
    region: oregon
    plan: standard # /month for production reliability

    repo: https://github.com/The-social-drink-company/sentia-ai-manufacturing-app
    branch: development
    rootDir: mcp-server

    buildCommand: npm install
    startCommand: npm start

    healthCheckPath: /health

    envVars:
      # Core Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: LOG_LEVEL
        value: info

      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true

      # AI Services - Claude (Anthropic)
      - key: ANTHROPIC_API_KEY
        sync: false # Set via Render dashboard for security

      # AI Services - OpenAI
      - key: OPENAI_API_KEY
        sync: false # Set via Render dashboard for security

      # Google AI (Optional)
      - key: GOOGLE_AI_API_KEY
        sync: false

      # Local LLM Configuration (Optional)
      - key: LOCAL_LLM_ENDPOINT
        value: http://localhost:11434
      - key: LOCAL_LLM_MODEL
        value: llama2

      # Database Connection (Using Render PostgreSQL from main app)
      # Note: This will use the same database as the main application
      # The connection string will be provided via environment group
      - key: DATABASE_URL
        sync: false # Will be set from Render environment group or dashboard
      
      # MCP Server specific environment variables
      - key: MCP_SERVER_PORT
        value: 3001
      - key: MCP_HTTP_PORT
        value: 3002
      - key: MCP_VECTOR_TABLE
        value: Embeddings
      - key: MCP_VECTOR_DIM
        value: 1536
      - key: BRANCH
        value: development

      # External Service APIs (For unified interface)
      # SECURITY: All API keys set via Render dashboard for security
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false

      - key: SHOPIFY_UK_API_KEY
        sync: false
      - key: SHOPIFY_UK_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_UK_SHOP_URL
        sync: false
      - key: SHOPIFY_USA_API_KEY
        sync: false
      - key: SHOPIFY_USA_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_USA_SHOP_URL
        sync: false

      - key: AMAZON_UK_MARKETPLACE_ID
        sync: false
      - key: AMAZON_USA_MARKETPLACE_ID
        sync: false

      - key: UNLEASHED_API_ID
        sync: false
      - key: UNLEASHED_API_KEY
        sync: false

      # CORS Settings - Updated to match actual Render URLs
      - key: CORS_ORIGINS
        value: https://sentia-manufacturing-dashboard-621h.onrender.com,https://sentia-manufacturing-dashboard-test.onrender.com,https://sentia-manufacturing-dashboard-production.onrender.com

      # WebSocket Configuration
      - key: ENABLE_WEBSOCKET
        value: true
      - key: WS_HEARTBEAT_INTERVAL
        value: 30000

      # Redis Cache (Optional)
      - key: REDIS_URL
        sync: false

      # Feature Flags
      - key: ENABLE_AI_FEATURES
        value: true
      - key: ENABLE_VECTOR_DB
        value: true
      - key: ENABLE_DECISION_ENGINE
        value: true
