"""Add comprehensive authentication features

Revision ID: 8f7b6d65ac0d
Revises: 0420cd0c943c
Create Date: 2025-08-26 16:40:47.221463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7b6d65ac0d'
down_revision = '0420cd0c943c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_ip_timestamp', ['ip_address', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_timestamp_type', ['timestamp', 'activity_type'], unique=False)
        batch_op.create_index('ix_audit_user_activity', ['user_id', 'activity_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('access_regions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('session_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('password_reset_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_reset_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('force_password_change')
        batch_op.drop_column('session_expires')
        batch_op.drop_column('session_token')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('access_regions')
        batch_op.drop_column('department')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_activity')
        batch_op.drop_index('ix_audit_timestamp_type')
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_activity_type'))
        batch_op.drop_index('ix_audit_ip_timestamp')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
